### ISSUE TITLE
Can not load main.css in development mode

### ISSUE THREAD

**Issue by gazatem** [catalin-luntraru/redux-minimal#5] opened 2016-10-11 14:04 UTC
Hi,

I've download and install the structure. However in development mode, css file is not loading.

**Comment by catalin-luntraru** [comment] 2016-10-11 19:33
There are 2 development modes:

- the script called "start" uses webpack-dev-server and all the css and js will be stored in memory. For this reason, if you open chrome console you can see that the css file missing. But its fine, because our css is in memory not on file
- the script called "build-dev" uses webpack to compile one js and one css file. And when you view index.html it will correctly include both css and js files and they will load.

So you can ignore the error for the css file when using the start script.

If that's not the issue, then please give more details?

**Comment by gazatem** [comment] 2016-10-12 05:54
great, solved the missing part.

I've had removed the missing css link in the head of index.html, I'm rather not to see any error.

**Comment by catalin-luntraru** [comment] 2016-10-12 06:00
Best would be to comment that line instead of removing it, because you will need to add it back when you build for deployment to either a dev or a production server.

**Comment by nbwar** [comment] 2016-10-18 18:23
@catalin-luntraru The issue is if you run `npm build-dev` then run `npm start` you will use both the stylesheet included in `index.html` and the stylesheet in memory from webpack. 

We need to way to either remove the build stylesheets upon `npm start` or to not include `main.css` if webpack hot reload is on.

**Comment by catalin-luntraru** [comment] 2016-10-19 08:28
Fixed by https://github.com/catalin-luntraru/redux-minimal/commit/ab74890ac2de4882b7a03dc556424e35754d7e67

**Comment by catalin-luntraru** [comment] 2016-10-19 08:29
Now we no longer get duplicated css and js files with webpac-dev-server.

We still have the complaint about the main.css file missing. Maybe we will fix that some day :)

**Closed by catalin-luntraru** 2016-10-19 08:29 UTC
